### ISSUE TITLE
try without MPICH_NEMESIS_ASYNC_PROGRESS

### ISSUE THREAD

**Issue by sebhtml** [GeneAssembly/biosal#717]
There is a huge variation in memory usage apparently.

**Comment by sebhtml** [comment]
None of the commits between 1082ef and f82e89 affects memory usage !

f82e787 transport: fix pami compilation error introduced in b49f6d85e6 ===> 30 GiB beagle-graph-soil-699-256x24-10 #699
5960ace remove conditional graph store count on Blue Gene /Q
39ad145 memory: move pool names outside of memory_pool.h
d2d62bb blue gene: disable work stealing
b49f6d8 core: change prefix for everything in core/ to core_
42f5a36 biosal: change prefix from bsal_ to biosal_
6d16c2f add API link
10ceac9 documentation: update API documentation
d1fa2ea documentation: fix action names in documentation
97420bc thorium: fix a race condition leading to a SIGSEGV
1082ef2 cray: build spate with gnu toolchain  ===> 20 GiB beagle-graph-soil-699-256x24-9 #699

**Comment by sebhtml** [comment]
**JobName**
**Machine**
**AllocationStatus**
**Path**
**Commit**
f82e7872289761319dd98a6527ef3310c1c75bd5

**Toolchain**
CrayCC

**Script**
**Submission**
**MachineUtilization**
**ComputationLoad**
**RunningTime**
**MemoryUtilization**
**Checksum**
**GoodComments**
**BadComments**
**NeutralComments**

**Comment by sebhtml** [comment]
The problem is not in NEMESIS.
Spate with GNU (#718 spate-gnu-718-256x24-2) uses 3 TiB less than Spate with Cray CC (#699 beagle-graph-soil-699-256x24-10).
